### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Omor12-2** [ethereum/remix-plugins-directory#391]
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/remix-plugins-directory/issues/387
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/remix-plugins-directory/issues/387
- [ ] https://github.com/ethereum/remix-plugins-directory/pull/384
- [ ] https://github.com/ethereum/remix-plugins-directory/pull/389
- [ ] https://github.com/ethereum/remix-plugins-directory/pull/386
- [x] 0x91b1c70941417e3efe4b3cf9bb7d38a1d5512712
```

**Comment by Omor12-2** [comment]
Release my asset

**Comment by Omor12-2** [comment]
Send coins in adding address now
